language: python
python:
    - "2.6"
    - "2.7"

env: LD_LIBRARY_PATH=/usr/local/lib

before_install:
    - "tests/before_install.sh"

install:
    - "pip install cffi==0.7"
    - "python setup.py install"

script: ./test.sh
