language: python
python:
    - "3.4"
    - "3.5"

env: LD_LIBRARY_PATH=/usr/local/lib
dist: trusty
before_install:
    - git clone https://github.com/google/re2.git
    - cd re2 && make && sudo make install

install:
    - pip install cffi >= 0.7 six

script: python3 setup.py test
