language: python
python:
    - "3.4"
    - "3.5"

env: LD_LIBRARY_PATH=/usr/local/lib
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libre2-dev -qq

install:
    - pip install cffi >= 0.7 six

script: python3 setup.py test
